# Generated by Django 6.1 on 2026-09-10 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('web_link', models.URLField(blank=True, null=True, unique=True)),
                ('image_path', models.FilePathField(unique=True)),
            ],
        ),
    ]
