# Generated by Django 6.1 on 2026-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_techstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
