# Generated by Django 6.1 on 2026-09-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_techstack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(default='w', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default='w', max_length=255),
            preserve_default=False,
        ),
    ]
