# Generated by Django 6.1 on 2026-09-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience_organization_experience_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='title',
        ),
    ]
