# Generated by Django 6.1 on 2026-09-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_experience_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechStack',
        ),
    ]
