# Generated by Django 6.1 on 2026-09-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_techstack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image_path',
        ),
        migrations.AddField(
            model_name='projects',
            name='image_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='web_link',
            field=models.URLField(blank=True),
        ),
    ]
