# Generated by Django 6.1 on 2026-09-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_projects_image_path_projects_image_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="thumbnail",
        ),
    ]
