# Generated by Django 6.1 on 2026-09-20 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_experience_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="started_at",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 9, 20, 18, 38, 55, 857198)
            ),
        ),
    ]
