# Generated by Django 6.0.7 on 2026-09-28 05:55

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_projects_starred_by_alter_experience_started_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="starred_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="starred_experience",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="started_at",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 9, 28, 12, 55, 46, 845111)
            ),
        ),
    ]
